// <auto-generated />
namespace VagasZM.Infra.Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VersaoInicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VersaoInicial));
        
        string IMigrationMetadata.Id
        {
            get { return "201710132241019_VersaoInicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
